"""Authentication and credential management for Philips Hue."""

import asyncio
import os

import keyring

SERVICE_NAME = "huesignal"
USERNAME = "huesignal"


class AuthError(Exception):
    """Raised when authentication fails."""


def get_app_key() -> str | None:
    """
    Get the app key from environment variable or keyring.

    Returns:
        The app key if found, None otherwise.
        HUESIGNAL_APP_KEY env var takes precedence over keyring.
    """
    # Check environment variable first
    env_key = os.environ.get("HUESIGNAL_APP_KEY")
    if env_key:
        return env_key

    # Fall back to keyring
    try:
        return keyring.get_password(SERVICE_NAME, USERNAME)
    except Exception:
        return None


def store_app_key(app_key: str) -> None:
    """
    Store the app key in Windows Credential Manager via keyring.

    Args:
        app_key: The app key to store

    Raises:
        AuthError: If storing the credential fails
    """
    try:
        keyring.set_password(SERVICE_NAME, USERNAME, app_key)
    except Exception as e:
        raise AuthError(f"Failed to store credential: {e}") from e


async def login(
    bridge_ip: str,
    timeout: float = 30.0,
) -> str:
    """
    Authenticate with Philips Hue bridge and return the app key.

    This implements the pairing flow where the user must press the link button
    on the bridge within the timeout period.

    Args:
        bridge_ip: IP address of the Hue bridge
        timeout: Maximum time to wait for link button press (default 30 seconds)

    Returns:
        The app key generated by the bridge

    Raises:
        AuthError: If authentication fails or times out
    """
    import httpx

    try:
        async with httpx.AsyncClient(verify=False, timeout=30.0) as client:
            url = f"https://{bridge_ip}/api"

            # Create a new app key via the pairing process
            # The bridge will return an app key if the link button was pressed
            start_time = asyncio.get_event_loop().time()
            while (asyncio.get_event_loop().time() - start_time) < timeout:
                try:
                    response = await client.post(
                        url,
                        json={
                            "devicetype": "huesignal",
                            "generateclientkey": True,
                        },
                    )
                    data = response.json()

                    # Check if successful
                    if isinstance(data, list) and len(data) > 0:
                        result = data[0]
                        if "success" in result:
                            # Extract the username (app key)
                            app_key = result["success"].get("username")
                            if app_key:
                                return app_key
                        elif "error" in result:
                            error_msg = result["error"].get("description", "Unknown error")
                            if "link button not pressed" in error_msg.lower():
                                # Link button not pressed yet, wait and retry
                                await asyncio.sleep(1)
                                continue
                            else:
                                raise AuthError(f"Bridge error: {error_msg}")
                except httpx.RequestError as e:
                    raise AuthError(f"Connection to bridge failed: {e}") from e

            raise AuthError(
                "Link button was not pressed within the timeout period. "
                "Please press the link button on your Hue Bridge and try again."
            )

    except AuthError:
        raise
    except Exception as e:
        raise AuthError(f"Authentication failed: {e}") from e
